### ISSUE TITLE
Incorrect reward for blue agent reaching max_steps

### ISSUE THREAD

**Issue by john-cardiff** [dstl/YAWNING-TITAN#10]
https://github.com/dstl/YAWNING-TITAN/blob/8c8a1af8f940b7060bc2a2484f34d898bad1cee4/yawning_titan/envs/generic/generic_env.py#L263

It should be the following.

                if self.network_interface.reward_end_multiplier:
                    # FIXED
                    reward = self.network_interface.reward_success * (
                        len(self.network_interface.get_nodes(filter_true_safe=True))
                        / self.network_interface.get_number_of_nodes()
                    )
                    # incorrect below
                    # reward = self.network_interface.reward_end_multiplier * (
                    #     len(self.network_interface.get_nodes(filter_true_safe=True))
                    #     / self.network_interface.get_number_of_nodes()
                    # )

since in the **NetworkInterface** class the variables are defined as following (although their names should likely be swapped).

        self.reward_success = self.reward_settings["rewards_for_reaching_max_steps"]
        self.reward_end_multiplier = self.reward_settings[
            "end_rewards_are_multiplied_by_end_state"
        ]

**Comment by jamesshort1** [comment]
Added as a new IDT Jira issue (AIDT-64)
