### ISSUE TITLE
Suggestion: adding the isolated state to observation

### ISSUE THREAD

**Issue by john-cardiff** [dstl/YAWNING-TITAN#12]
https://github.com/dstl/YAWNING-TITAN/blob/6457037045db93bb63a74f0edd335e9054437b28/yawning_titan/envs/generic/core/network_interface.py#L816

Including **isolation_status** to **OBSERVATION_SPACE** in the configuration file, and then adding the if statement in **get_current_observation**, as the agent will struggle in training with isolate/connect without it (since it currently needs to understand more complex relationships with the adjacency matrix). A simple fix in the meantime is below.

        # Gets the adj matrix for the current graph
        node_connections = []

        # ADDED
        isolated_state = []

        if self.obs_node_connections:
            node_connections = self.adj_matrix
            # pads the array to account for any missing deceptive nodes that may not have been placed yet
            node_connections = np.pad(node_connections, (0, open_spaces), "constant")

            # ADDED
            isolated_state = np.asarray(
                list(self.get_attributes_from_key("isolated").values())
            ).astype(int)
            # does it make sense to isolate a deceptive node?
            isolated_state = np.pad(isolated_state, (0, open_spaces), "constant")

then including the variable in the **obs**, and making the required changes in **get_observation_size**. With this change it might also make sense for the **node_connections** to remain static despite nodes being isolated. This intuitively makes sense since the decision of reconnecting a node will depend on the true adjacency matrix.

**Comment by jamesshort1** [comment]
Added as a new IDT Jira issue (AIDT-66)
