### ISSUE TITLE
high_value_target is always "None" if "gr_loss_hvt" = False, network_interface 

### ISSUE THREAD

**Issue by A-acuto** [dstl/YAWNING-TITAN#17]
Hi, 

I am working on some custom networks along with longer game scenarios (e.g., we don't care, at the moment, if the _high_value_target_ is taken or not). I have a specific node which I identify as _high_value_target_ and I feed it into the class _network_interface_. 

However, it seems that if I set from the setup YAML file _gr_loss_hvt_ = _False_, the class automatically forgets the input_value_target and sets it to '_None_' (see line 408 in network_interface.py file). 

So the getter function, _get_high_value_target_, return "_None_", which is set in the __init__ function of the class (lines 403 to 408).

I fixed it by changing the output (from "None" to "high_value_target") in case I have "_gr_loss_hvt = False_" in the YAML file.

However, it seems that the function is missing a description for cases like "_gr_loss_hvt = False_".

Hope this helps, 
Cheers

**Comment by jamesshort1** [comment]
Thank you for your post. We have now assigned your issue to the Yawning Titan development backlog with the view to address in a future sprint.

**Comment by A-acuto** [comment]
Hi @ChrisMcCarthyDev , this update should fix that issue. Many thanks
Looking forward to see v1.0.0 release

**Comment by ChrisMcCarthyDev** [comment]
Closing this issue as fix applied in https://github.com/dstl/YAWNING-TITAN/releases/tag/v1.0.0
