### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Autonomous-Resilient-Cyber-Defence** [dstl/YAWNING-TITAN#33]
Link to paper explaining the NSA example environment does not work.

https://dstl.github.io/YAWNING-TITAN/source/_autosummary/yawning_titan.envs.specific.nsa_node_def.html

**Comment by RogerBearpark** [comment]
The team will take a look at the reported issue which has been added to our backlog with reference AIDT-160

**Comment by ChrisMcCarthyDev** [comment]
This is linked to a previous PR (https://github.com/dstl/YAWNING-TITAN/pull/13). Seems some of the broken links were missed. Fix will be applied in the next release. 

[Link to the intended Ridley, A. (2017) research paper](https://www.nsa.gov/portals/75/documents/resources/everyone/digital-media-center/publications/the-next-wave/TNW-22-1.pdf#page=9)
