### ISSUE TITLE
Typo in the Citation section

### ISSUE THREAD

**Issue by A-acuto** [dstl/YAWNING-TITAN#48]
In the Readme file in the front page there is a very small typo in the Andrew et al. paper citation: Conference is written _Confernece_
Below it is highlighted in the citation
@inproceedings{...
...
 title = {Developing Optimal Causal Cyber-Defence Agents via Cyber Security Simulation},
 maintitle = {International **Confernece** on Machine Learning (ICML)},
 booktitle = {Workshop on Machine Learning for Cybersecurity (ML4Cyber)}
}

**Comment by ChrisMcCarthyDev** [comment]
Hi @A-acuto,

Thanks for posting this. This will be updated in the next release (2.0.0).
