### ISSUE TITLE
high_value_target not working with lose_when_high_value_target_lost setting (i.e self.gr_loss_hvt is True)

### ISSUE THREAD

**Issue by john-cardiff** [dstl/YAWNING-TITAN#7]
https://github.com/dstl/YAWNING-TITAN/blob/8c8a1af8f940b7060bc2a2484f34d898bad1cee4/yawning_titan/envs/generic/core/network_interface.py#L370

quick fix: 

        self.possible_high_value_targets = [] if high_value_target is None else [high_value_target]

As a sidenote, it will only select a random new hvt if new random entry nodes are also set, i.e in the RESET part of the config file

      choose_new_high_value_target_on_reset: False
      choose_new_entry_nodes_on_reset: False

but not an issue in my opinion as I can't think of a case where the hvt changes but the entry nodes need to remain the same on resets.

**Comment by jamesshort1** [comment]
Could be tied into the work on defining high value nodes. Can Stefen/Chris L review this issue and see whether it’s related

**Comment by ChrisMcCarthyDev** [comment]
Hi @john-cardiff. Thank you for raising this. Please could you review my comments in [high_value_target is always "None" if "gr_loss_hvt" = False, network_interface #17](https://github.com/dstl/YAWNING-TITAN/issues/17), as I believe the newly implemented logic that is about to be released in v1.0.0 (today hopefully) addresses this issue.

**Comment by ChrisMcCarthyDev** [comment]
Closing this issue as fix applied in https://github.com/dstl/YAWNING-TITAN/releases/tag/v1.0.0
