### ISSUE TITLE
Isolation cost/reward

### ISSUE THREAD

**Issue by john-cardiff** [dstl/YAWNING-TITAN#9]
https://github.com/dstl/YAWNING-TITAN/blob/8c8a1af8f940b7060bc2a2484f34d898bad1cee4/yawning_titan/envs/generic/core/reward_functions.py#L80

Blue agents can simply isolate entry nodes and incur the one step cost with no further penalties throughout the episode (or isolate other nodes such as the hvt). The isolation cost should be incurred at each step until the node is reconnected. An example implementation in standard_rewards is shown below. 

    # cost for actions
    action_cost = {
        "reduce_vulnerability": 0.5,
        "restore_node": 1,
        "make_node_safe": 0.5,
        "scan": 0,
        "isolate": 10, # should be less or equal to restore_node cost for a step, so between 0.5 and 1 instead of 10
        "connect": 0,
        "do_nothing": -0.5,
        "add_deceptive_node": 8,
    }

    # don't count isolation cost twice
    reward = -action_cost[blue_action] if blue_action != "isolate" else 0
    # while nodes are still isolated include the "isolate" cost
    reward += -action_cost["isolate"] * sum(end_isolation.values())

**Comment by jamesshort1** [comment]
Added as a new IDT Jira issue (AIDT-63)
